# Generated by Django 4.2.4 on 2023-09-02 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="institude",
            new_name="institute",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
