# Generated by Django 4.2.4 on 2023-08-26 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('requisitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='status',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_status', to='requisitions.requisition'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_author', to='users.profile'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisitions.project'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='requisition_tags', to='requisitions.tag'),
        ),
        migrations.AddField(
            model_name='project',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_advisor', to='users.profile'),
        ),
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_author', to='users.profile'),
        ),
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='event',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_event', to='requisitions.requisition'),
        ),
        migrations.AddField(
            model_name='deliver',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='deliver',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_deliver', to='requisitions.requisition'),
        ),
    ]
