# Generated by Django 4.2.4 on 2023-08-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ceua_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/ceua'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/projects'),
        ),
    ]
