# Generated by Django 4.2.4 on 2023-08-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requisitions", "0003_alter_project_ceua_file_alter_project_project_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliver",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
