# Generated by Django 4.2.4 on 2023-08-30 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("requisitions", "0004_deliver_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("males", models.PositiveSmallIntegerField(default=0)),
                ("females", models.PositiveSmallIntegerField(default=0)),
                ("notes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.profile"
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisition_delivery",
                        to="requisitions.requisition",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Deliver",
        ),
    ]
